import model.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        Mobile iPhone2 = new iPhone();
        System.out.println(iPhone2.call("sample"));

        Mobile iPhone = new iPhone();
        iPhone.setName("Chloe");
        iPhone.setBrand("iPhone");
        iPhone.setColor("Yellow");
        System.out.println(iPhone.info());

        Mobile android = new AndroidMobile();
        android.setName("Chloe");
        android.setBrand("android");
        android.setColor("Yellow");
        System.out.println(android.info());


        Person personIPhone = new Person();
        personIPhone.setPhone(iPhone);
        personIPhone.setName("Chloe");
        System.out.println(personIPhone.makeCall());

        Person androidIPhone = new Person();
        androidIPhone.setPhone(android);
        androidIPhone.setName("Chloe");
        System.out.println(androidIPhone.makeCall());

        iPhoneRobot robot = new iPhoneRobot();
        iPhone iPhone1 = new iPhone();
        robot.setiPhone(iPhone1);
        System.out.println(robot.makeCall());
    }
}
