import model.AndroidMobile;
import model.Mobile;
import model.iPhone;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        Mobile mobile = new AndroidMobile();
        System.out.println(mobile.call("sample"));
    }
}
